// Placeholder replacement engine for letter templates
// Placeholders use the format @@placeholder_name@@

export const TEMPLATE_PLACEHOLDERS = [
  // School
  { key: 'school_name',    label: 'School Name',    category: 'School' },
  { key: 'school_address', label: 'School Address', category: 'School' },
  { key: 'school_email',   label: 'School Email',   category: 'School' },
  { key: 'school_phone',   label: 'School Phone',   category: 'School' },
  { key: 'school_city',    label: 'School City',    category: 'School' },
  { key: 'school_website', label: 'School Website', category: 'School' },
  { key: 'school_logo',    label: 'School Logo (img tag)', category: 'School' },
  // Student
  { key: 'student_name',         label: 'Student Full Name',   category: 'Student' },
  { key: 'student_first_name',   label: 'Student First Name',  category: 'Student' },
  { key: 'student_last_name',    label: 'Student Last Name',   category: 'Student' },
  { key: 'student_admission_no', label: 'Admission Number',    category: 'Student' },
  { key: 'student_class',        label: 'Class Name',          category: 'Student' },
  { key: 'student_grade',        label: 'Grade',               category: 'Student' },
  { key: 'student_section',      label: 'Section',             category: 'Student' },
  // Invoice
  { key: 'invoice_no',      label: 'Invoice Number',   category: 'Invoice' },
  { key: 'invoice_date',    label: 'Invoice Date',     category: 'Invoice' },
  { key: 'due_date',        label: 'Due Date',         category: 'Invoice' },
  { key: 'amount',          label: 'Total Amount',     category: 'Invoice' },
  { key: 'paid_amount',     label: 'Amount Paid',      category: 'Invoice' },
  { key: 'balance_due',     label: 'Balance Due',      category: 'Invoice' },
  { key: 'status',          label: 'Payment Status',   category: 'Invoice' },
  { key: 'installment_no',  label: 'Installment No.',  category: 'Invoice' },
  { key: 'description',     label: 'Description',      category: 'Invoice' },
  { key: 'academic_year',   label: 'Academic Year',    category: 'Invoice' },
  // General
  { key: 'generated_date', label: 'Generated Date', category: 'General' },
  { key: 'generated_by',   label: 'Generated By',   category: 'General' },
] as const;

export type PlaceholderKey = (typeof TEMPLATE_PLACEHOLDERS)[number]['key'];

export function renderTemplate(
  html: string,
  data: Partial<Record<PlaceholderKey | string, string>>
): string {
  return html.replace(/@@([a-z_]+)@@/g, (_, key: string) => {
    return data[key] !== undefined && data[key] !== null ? String(data[key]) : `@@${key}@@`;
  });
}

export function validateTemplate(html: string): { valid: boolean; unknownKeys: string[] } {
  const found: string[] = [];
  html.replace(/@@([a-z_]+)@@/g, (_, key) => { found.push(key); return ''; });
  const knownKeys = new Set(TEMPLATE_PLACEHOLDERS.map(p => p.key));
  const unknownKeys = found.filter(k => !knownKeys.has(k as PlaceholderKey));
  return { valid: unknownKeys.length === 0, unknownKeys };
}
