/**
 * Canonical KPI definitions — single source of truth for 37 KPIs across 3 segments / 8 categories.
 * Per-school configuration (target, enabled/disabled, role visibility, formula params) is stored
 * in SchoolKpiConfig and loaded via /api/super-admin/kpi-config.
 * Actual values are computed on-the-fly in /api/performance/kpi.
 */

export type KpiSegment =
  | 'academic_performance'
  | 'attendance'
  | 'behavior';

export type KpiCategory =
  | 'student_performance'
  | 'attendance'
  | 'teacher_performance'
  | 'operational'
  | 'discipline'
  | 'cocurricular'
  | 'ai_smart';

export type KpiDirection = 'above' | 'below';

export interface FormulaParamDef {
  key:          string;
  label:        string;
  defaultValue: number;
  unit?:        string;
  min?:         number;
  max?:         number;
}

export interface KpiDef {
  code:             string;
  name:             string;
  description:      string;
  segment:          KpiSegment;
  category:         KpiCategory;
  unit:             string;        // '%', 'count', 'score', 'days', 'hours', 'rating'
  higherIsBetter:   boolean;
  defaultTarget:    number;
  targetDirection:  KpiDirection;
  dataSource:       string;
  visibleTo:        string[];      // default role visibility (can be overridden per school)
  formulaParamDefs?: FormulaParamDef[];
}

export const KPI_DEFINITIONS: KpiDef[] = [

  // ── Segment: Academic Performance → Student Performance ────────────────────
  {
    code: 'student_avg_score',
    name: 'Overall Academic Score',
    description: 'Average of all subject marks across all exams',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 75,
    targetDirection: 'above',
    dataSource: 'ExamResult',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher', 'parent', 'student'],
  },
  {
    code: 'pass_percentage',
    name: 'Pass Percentage',
    description: 'Percentage of students who passed (≥ passing mark threshold)',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 95,
    targetDirection: 'above',
    dataSource: 'ExamResult + Exam.passingMarks',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
    formulaParamDefs: [
      { key: 'passingPct', label: 'Passing Marks %', defaultValue: 40, unit: '%', min: 1, max: 100 },
    ],
  },
  {
    code: 'subject_performance',
    name: 'Subject Performance',
    description: 'Average marks per subject across the school',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 70,
    targetDirection: 'above',
    dataSource: 'ExamResult grouped by subject',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'improvement_rate',
    name: 'Improvement Rate',
    description: 'Average student score improvement: current term vs previous term',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 0,
    targetDirection: 'above',
    dataSource: 'ExamResult (multi-term comparison)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher', 'parent', 'student'],
  },
  {
    code: 'top_performer_ratio',
    name: 'Top Performer Ratio',
    description: 'Percentage of students scoring above the top-performer threshold',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 20,
    targetDirection: 'above',
    dataSource: 'ExamResult',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
    formulaParamDefs: [
      { key: 'topPct', label: 'Top Performer Threshold', defaultValue: 90, unit: '%', min: 50, max: 100 },
    ],
  },
  {
    code: 'weak_student_ratio',
    name: 'Weak Student Ratio',
    description: 'Percentage of students scoring below the weak-student threshold',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: false,
    defaultTarget: 5,
    targetDirection: 'below',
    dataSource: 'ExamResult',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
    formulaParamDefs: [
      { key: 'weakPct', label: 'Weak Student Threshold', defaultValue: 40, unit: '%', min: 1, max: 80 },
    ],
  },
  {
    code: 'homework_completion_rate',
    name: 'Homework Completion Rate',
    description: 'Percentage of assigned homework submitted (on time or late)',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 90,
    targetDirection: 'above',
    dataSource: 'HomeworkSubmission',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher', 'parent'],
  },
  {
    code: 'assignment_delay_rate',
    name: 'Assignment Delay Rate',
    description: 'Percentage of homework submissions marked as late',
    segment: 'academic_performance',
    category: 'student_performance',
    unit: '%',
    higherIsBetter: false,
    defaultTarget: 10,
    targetDirection: 'below',
    dataSource: 'HomeworkSubmission (status=late)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },

  // ── Segment: Academic Performance → Teacher Performance ───────────────────
  {
    code: 'result_improvement_rate',
    name: 'Student Result Improvement',
    description: 'Average change in student scores term-over-term for the teacher\'s class',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 0,
    targetDirection: 'above',
    dataSource: 'ExamResult (multi-term comparison)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'assignment_evaluation_time',
    name: 'Assignment Evaluation Time',
    description: 'Average days taken to evaluate and return homework/assignments',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: 'days',
    higherIsBetter: false,
    defaultTarget: 3,
    targetDirection: 'below',
    dataSource: 'HomeworkSubmission (submit → graded date gap)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'classroom_engagement_score',
    name: 'Classroom Engagement Score',
    description: 'Composite score from student feedback and participation metrics',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: 'score',
    higherIsBetter: true,
    defaultTarget: 75,
    targetDirection: 'above',
    dataSource: 'StudentFeedback',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'lesson_completion_rate',
    name: 'Lesson Completion Rate',
    description: 'Percentage of planned syllabus items marked complete',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 90,
    targetDirection: 'above',
    dataSource: 'SyllabusItem',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'parent_feedback_rating',
    name: 'Parent Feedback Rating',
    description: 'Average parent satisfaction rating from PTM and feedback forms',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: 'rating',
    higherIsBetter: true,
    defaultTarget: 4,
    targetDirection: 'above',
    dataSource: 'ParentFeedback',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
    formulaParamDefs: [
      { key: 'maxRating', label: 'Max Rating Scale', defaultValue: 5, min: 5, max: 10 },
    ],
  },
  {
    code: 'digital_usage_score',
    name: 'Digital Usage Score',
    description: 'ERP/LMS usage frequency — exams entered, homework assigned, attendance marked',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: 'score',
    higherIsBetter: true,
    defaultTarget: 80,
    targetDirection: 'above',
    dataSource: 'Exam + Homework + Attendance (teacher activity)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'teacher_attendance_consistency',
    name: 'Attendance Consistency',
    description: 'Teacher\'s own attendance rate over the period',
    segment: 'academic_performance',
    category: 'teacher_performance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 95,
    targetDirection: 'above',
    dataSource: 'Attendance (teacher)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },

  // ── Segment: Academic Performance → Operational ───────────────────────────
  {
    code: 'fee_collection_efficiency',
    name: 'Fee Collection Efficiency',
    description: 'Percentage of total billed fees collected (paid ÷ total)',
    segment: 'academic_performance',
    category: 'operational',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 95,
    targetDirection: 'above',
    dataSource: 'FeeInvoice (status=paid)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'transport_punctuality',
    name: 'Transport Punctuality',
    description: 'Percentage of bus rides arriving/departing within the scheduled window',
    segment: 'academic_performance',
    category: 'operational',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 90,
    targetDirection: 'above',
    dataSource: 'TransportRide (actual vs scheduled time)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'complaint_resolution_time',
    name: 'Complaint Resolution Time',
    description: 'Average hours to resolve student/parent queries',
    segment: 'academic_performance',
    category: 'operational',
    unit: 'hours',
    higherIsBetter: false,
    defaultTarget: 48,
    targetDirection: 'below',
    dataSource: 'StudentQuery (createdAt → resolvedAt)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'admission_conversion_rate',
    name: 'Admission Conversion Rate',
    description: 'Percentage of admission applications that converted to enrolment',
    segment: 'academic_performance',
    category: 'operational',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 60,
    targetDirection: 'above',
    dataSource: 'AdmissionApplication (status=enrolled)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'system_usage_rate',
    name: 'System Usage Rate',
    description: 'Percentage of active staff who have used the ERP in the last 30 days',
    segment: 'academic_performance',
    category: 'operational',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 85,
    targetDirection: 'above',
    dataSource: 'User.lastLoginAt (staff users)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },

  // ── Segment: Academic Performance → Co-Curricular ─────────────────────────
  {
    code: 'cocurricular_participation_rate',
    name: 'Student Participation Rate',
    description: 'Percentage of students participating in at least one co-curricular activity',
    segment: 'academic_performance',
    category: 'cocurricular',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 60,
    targetDirection: 'above',
    dataSource: 'EventParticipant',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'sports_achievement_score',
    name: 'Sports Achievement Score',
    description: 'Aggregate score based on medals and certificates earned in sports events',
    segment: 'academic_performance',
    category: 'cocurricular',
    unit: 'score',
    higherIsBetter: true,
    defaultTarget: 50,
    targetDirection: 'above',
    dataSource: 'EventParticipant (sports events, result=medal/certificate)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'event_engagement_rate',
    name: 'Event Engagement Rate',
    description: 'Average student attendance rate across school events',
    segment: 'academic_performance',
    category: 'cocurricular',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 70,
    targetDirection: 'above',
    dataSource: 'EventParticipant + SchoolEvent',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'club_participation',
    name: 'Club Participation',
    description: 'Percentage of students enrolled in at least one school club',
    segment: 'academic_performance',
    category: 'cocurricular',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 50,
    targetDirection: 'above',
    dataSource: 'EventParticipant (club-type events)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },

  // ── Segment: Academic Performance → AI Smart KPIs ────────────────────────
  {
    code: 'learning_risk_score',
    name: 'Learning Risk Score',
    description: 'AI composite risk score based on attendance, marks, and homework (0–100, higher = more at risk)',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'score',
    higherIsBetter: false,
    defaultTarget: 30,
    targetDirection: 'below',
    dataSource: 'ExamResult + Attendance + HomeworkSubmission',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
    formulaParamDefs: [
      { key: 'highRiskThreshold', label: 'High Risk Threshold', defaultValue: 60, min: 40, max: 90 },
      { key: 'medRiskThreshold',  label: 'Medium Risk Threshold', defaultValue: 30, min: 10, max: 59 },
      { key: 'weightMarks',       label: 'Marks Weight (%)',      defaultValue: 40, min: 10, max: 80 },
      { key: 'weightAttendance',  label: 'Attendance Weight (%)', defaultValue: 35, min: 10, max: 80 },
      { key: 'weightHomework',    label: 'Homework Weight (%)',   defaultValue: 25, min: 10, max: 80 },
    ],
  },
  {
    code: 'burnout_indicator',
    name: 'Burnout Indicator',
    description: 'Students showing sudden decline in attendance + homework + performance',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 0,
    targetDirection: 'below',
    dataSource: 'Attendance + HomeworkSubmission + ExamResult (trend)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'attention_drop_detection',
    name: 'Attention Drop Detection',
    description: 'Students showing sudden decline in engagement metrics over the last 2 weeks',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 0,
    targetDirection: 'below',
    dataSource: 'Attendance + HomeworkSubmission (recent trend)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'subject_difficulty_index',
    name: 'Subject Difficulty Index',
    description: 'Subjects with the highest failure rates — indicates curriculum gaps',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'score',
    higherIsBetter: false,
    defaultTarget: 20,
    targetDirection: 'below',
    dataSource: 'ExamResult (fail rate per subject)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'teacher_workload_score',
    name: 'Teacher Workload Score',
    description: 'Composite score of assignment volume and schedule density per teacher',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'score',
    higherIsBetter: false,
    defaultTarget: 70,
    targetDirection: 'below',
    dataSource: 'Homework + Timetable + Exam (teacher activity)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'at_risk_student_count',
    name: 'Students at Risk',
    description: 'Number of students classified as high or medium learning risk',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 0,
    targetDirection: 'below',
    dataSource: 'ExamResult + Attendance + HomeworkSubmission',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'parent_engagement_risk',
    name: 'Parent Engagement Risk',
    description: 'Parents with low portal activity in the last 30 days (no login, no query)',
    segment: 'academic_performance',
    category: 'ai_smart',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 0,
    targetDirection: 'below',
    dataSource: 'StudentQuery + parent activity',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },

  // ── Segment: Attendance ───────────────────────────────────────────────────
  {
    code: 'student_attendance_pct',
    name: 'Student Attendance %',
    description: 'Average student attendance as a percentage of working days',
    segment: 'attendance',
    category: 'attendance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 90,
    targetDirection: 'above',
    dataSource: 'Attendance (student)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher', 'parent', 'student'],
  },
  {
    code: 'chronic_absenteeism',
    name: 'Chronic Absenteeism Rate',
    description: 'Percentage of students with attendance below the chronic threshold',
    segment: 'attendance',
    category: 'attendance',
    unit: '%',
    higherIsBetter: false,
    defaultTarget: 5,
    targetDirection: 'below',
    dataSource: 'Attendance (student)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
    formulaParamDefs: [
      { key: 'chronicThreshold', label: 'Chronic Absentee Threshold', defaultValue: 75, unit: '%', min: 50, max: 90 },
    ],
  },
  {
    code: 'teacher_attendance_pct',
    name: 'Teacher Attendance %',
    description: 'Average teacher attendance rate',
    segment: 'attendance',
    category: 'attendance',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 95,
    targetDirection: 'above',
    dataSource: 'Attendance (teacher)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
  {
    code: 'late_arrival_rate',
    name: 'Late Arrival Rate',
    description: 'Percentage of attendance records marked as "late"',
    segment: 'attendance',
    category: 'attendance',
    unit: '%',
    higherIsBetter: false,
    defaultTarget: 3,
    targetDirection: 'below',
    dataSource: 'Attendance (status=late)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },

  // ── Segment: Behavior ─────────────────────────────────────────────────────
  {
    code: 'discipline_incident_count',
    name: 'Discipline Incident Count',
    description: 'Monthly count of logged behavior incidents',
    segment: 'behavior',
    category: 'discipline',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 5,
    targetDirection: 'below',
    dataSource: 'BehaviorIncident',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'positive_behavior_ratio',
    name: 'Positive Behavior Ratio',
    description: 'Ratio of positive behavior records to total incidents',
    segment: 'behavior',
    category: 'discipline',
    unit: '%',
    higherIsBetter: true,
    defaultTarget: 70,
    targetDirection: 'above',
    dataSource: 'BehaviorIncident (type=positive vs negative)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod', 'teacher'],
  },
  {
    code: 'counseling_requirement_rate',
    name: 'Counseling Requirement Rate',
    description: 'Percentage of students flagged as needing counseling intervention',
    segment: 'behavior',
    category: 'discipline',
    unit: '%',
    higherIsBetter: false,
    defaultTarget: 5,
    targetDirection: 'below',
    dataSource: 'BehaviorIncident (severity=high / counseling flag)',
    visibleTo: ['super_admin', 'school_admin', 'principal', 'hod'],
  },
  {
    code: 'bullying_reports',
    name: 'Bullying Reports',
    description: 'Monthly count of bullying incidents reported',
    segment: 'behavior',
    category: 'discipline',
    unit: 'count',
    higherIsBetter: false,
    defaultTarget: 0,
    targetDirection: 'below',
    dataSource: 'BehaviorIncident (type=bullying)',
    visibleTo: ['super_admin', 'school_admin', 'principal'],
  },
];

/** Quick lookup by code */
export const KPI_MAP: Record<string, KpiDef> = Object.fromEntries(
  KPI_DEFINITIONS.map(k => [k.code, k]),
);

export const KPI_CATEGORIES: Record<KpiCategory, string> = {
  student_performance: 'Student Performance',
  attendance:          'Attendance',
  teacher_performance: 'Teacher Performance',
  operational:         'Operational',
  discipline:          'Discipline & Behavior',
  cocurricular:        'Co-Curricular',
  ai_smart:            'AI Smart KPIs',
};

export const KPI_SEGMENTS: Record<KpiSegment, { label: string; categories: KpiCategory[] }> = {
  academic_performance: {
    label: 'Academic Performance',
    categories: ['student_performance', 'teacher_performance', 'operational', 'cocurricular', 'ai_smart'],
  },
  attendance: {
    label: 'Attendance',
    categories: ['attendance'],
  },
  behavior: {
    label: 'Behavior',
    categories: ['discipline'],
  },
};
